"""Common dataset loaders. Encodes the data-folder policy:

  - **raw**:       external datasets under ``data/raw/`` (gitignored; fetched on
                   demand or placed manually — see ``data/raw/README.md``)
  - **generated**: derived-from-raw and synthetic data under ``data/generated/``
                   (gitignored by default; canonical/expensive outputs committed)

For raw datasets where automatic fetching is impractical or licensing is
unclear, readers must place files manually — see ``data/raw/README.md``.
"""
from __future__ import annotations

import shutil
from pathlib import Path

import pandas as pd

from msbook.paths import DATA_DIR


# =============================================================================
# Generated tier — derived/synthetic data committed in repo (data/generated/)
# =============================================================================

def load_mmm_synthetic() -> pd.DataFrame:
    """Bundled synthetic MMM dataset used by Part 6 chapters.

    Loaded from ``data/generated/part6/sec6.2-mmm/mmm_synthetic_data.csv``.
    Generated by the script alongside the dataset (see directory README).
    """
    path = DATA_DIR / "generated" / "part6" / "sec6.2-mmm" / "mmm_synthetic_data.csv"
    if not path.exists():
        raise FileNotFoundError(
            f"Expected synthetic file at {path}. "
            "Run notebooks/part6-media-optimization/mmm_data_generation.py to regenerate."
        )
    return pd.read_csv(path)


# =============================================================================
# Raw tier — external datasets under data/raw/ (gitignored)
# =============================================================================

def load_online_retail_ii(clean: bool = True) -> pd.DataFrame:
    """Online Retail II (UCI ML / Kaggle, CC0, ~95 MB manual download).

    Reads ``data/raw/Online_Retail_II_UCI/online_retail_II.csv``.
    The file is not redistributed in the repo; see ``data/raw/README.md`` for
    how to obtain it.

    Parameters
    ----------
    clean : if True (default), drop cancellations (Invoice starts with 'C'),
        drop rows with null Customer ID, cast Customer ID to int→str,
        drop rows with non-positive Quantity or Price, and add a Revenue column.
    """
    path = DATA_DIR / "raw" / "Online_Retail_II_UCI" / "online_retail_II.csv"
    if not path.exists():
        raise FileNotFoundError(
            "online_retail_II.csv not found. It is a ~95 MB manual download (CC0); "
            "get it from https://archive.ics.uci.edu/dataset/502/online+retail+ii "
            f"and place it at {path} (see data/raw/README.md)."
        )
    df = pd.read_csv(path, parse_dates=["InvoiceDate"])

    if clean:
        df = df[
            ~df["Invoice"].astype(str).str.startswith("C")
            & df["Customer ID"].notna()
        ].copy()
        df["Customer ID"] = df["Customer ID"].astype(int).astype(str)
        df = df[(df["Quantity"] > 0) & (df["Price"] > 0)].copy()
        df["Revenue"] = df["Quantity"] * df["Price"]

    return df


def load_dunnhumby(file: str = "transaction_data.csv") -> pd.DataFrame:
    """Raw dataset: Dunnhumby — The Complete Journey (Kaggle).

    Fetches via ``kagglehub`` on first use; cached at
    ``data/raw/Dunnhumby_kaggle/`` (gitignored). Requires ``kaggle.json``
    credentials — see ``data/raw/README.md``.
    """
    target_dir = DATA_DIR / "raw" / "Dunnhumby_kaggle"
    target = target_dir / file
    if not target.exists():
        try:
            import kagglehub  # type: ignore[import-not-found]
        except ImportError as e:
            raise ImportError(
                "kagglehub is required to fetch Dunnhumby. Install with "
                "`pip install kagglehub` or `conda install -c conda-forge kagglehub`."
            ) from e
        cache_path = kagglehub.dataset_download(
            "frtgnn/dunnhumby-the-complete-journey"
        )
        target_dir.mkdir(parents=True, exist_ok=True)
        for f in Path(cache_path).iterdir():
            shutil.copy(f, target_dir / f.name)
    return pd.read_csv(target)


# Canonical source for the MineThatData E-Mail Analytics challenge dataset.
_MINETHATDATA_URL = (
    "http://www.minethatdata.com/"
    "Kevin_Hillstrom_MineThatData_E-MailAnalytics_DataMiningChallenge_2008.03.20.csv"
)


def load_minethatdata() -> pd.DataFrame:
    """Raw dataset: Kevin Hillstrom's MineThatData e-mail challenge.

    A 64,000-customer e-mail marketing experiment (Kevin Hillstrom,
    MineThatData). Customers were randomized into three arms — a Men's
    merchandise e-mail, a Women's merchandise e-mail, and a no-e-mail control —
    and observed for two weeks of ``visit``, ``conversion``, and ``spend``.
    Columns: ``recency, history_segment, history, mens, womens, zip_code,
    newbie, channel, segment, visit, conversion, spend``.

    Source: Kevin Hillstrom, *The MineThatData E-Mail Analytics And Data Mining
    Challenge* (2008). https://blog.minethatdata.com/2008/03/minethatdata-e-mail-analytics-and-data.html

    Fetched on first use from the original CSV URL and cached (gitignored) at
    ``data/raw/minethatdata/``. The raw CSV is not redistributed in this
    repository. Raises ``RuntimeError`` if the source is unreachable rather than
    silently falling back to unrelated data.
    """
    cache_dir = DATA_DIR / "raw" / "minethatdata"
    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_path = cache_dir / "hillstrom_email.csv"

    if not cache_path.exists():
        from urllib.error import URLError
        from urllib.request import urlopen

        try:
            with urlopen(_MINETHATDATA_URL, timeout=30) as resp:  # noqa: S310
                raw = resp.read()
        except (URLError, OSError) as e:
            raise RuntimeError(
                "Could not fetch the MineThatData dataset from "
                f"{_MINETHATDATA_URL}. The original source appears to be "
                "unavailable. Check your network connection or download the "
                f"CSV manually to {cache_path}. This loader does not fall back "
                "to any substitute dataset."
            ) from e
        cache_path.write_bytes(raw)

    return pd.read_csv(cache_path)

